const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('integrated.html','utf8');
const start=html.indexOf('let _ttsGeneration=0;');
const end=html.indexOf('let _ttsCapabilityPromise',start);
const timers=[];
const context=vm.createContext({setTimeout:(fn,delay)=>{timers.push({fn,delay});return timers.length;}});
vm.runInContext(html.slice(start,end),context);
vm.runInContext('var calls=0;_speechStartAction=()=>calls++;notifySpeechStarted(0,120);notifySpeechStarted(0,120);',context);
assert.equal(timers.length,1,'Only first audio chunk schedules motion');
assert.equal(timers[0].delay,120,'Respect actual scheduled audio start');
timers[0].fn();
assert.equal(vm.runInContext('calls',context),1);
vm.runInContext('notifySpeechStarted(0)',context);
assert.equal(timers.length,1,'Do not replay motion for later chunks');
vm.runInContext('_speechStartAction=()=>calls++;notifySpeechStarted(0);_ttsGeneration++;',context);
timers[1].fn();
assert.equal(vm.runInContext('calls',context),1,'Cancelled audio must not trigger stale motion');
assert(!html.includes('setTimeout(()=>playMotion(msg.motion),200)'));
assert(html.includes("im.on('beforeModelUpdate',()=>{"),'Apply lips after native motion and physics before core render');
assert.equal(vm.runInContext('streamChunkBytes(24000,false)',context),15360);
assert.equal(vm.runInContext('streamChunkBytes(24000,true)',context),7680);
assert.equal(vm.runInContext('streamStartTime(1,2,true)',context),2,'Continuous chunks must not insert gaps');
assert.equal(vm.runInContext('streamStartTime(3,2,true)',context),3.2,'Buffer starvation must rebuffer');
const lipStart=html.indexOf('function _getLipSyncTarget(');
const lipEnd=html.indexOf('function toggleTTS()',lipStart);
const lipContext=vm.createContext({ttsSpeaking:true,_useBrowserTTS:false,_timeDomainData:null,
  _analyser:{fftSize:256,getByteTimeDomainData:data=>data.fill(128)}});
vm.runInContext(html.slice(lipStart,lipEnd),lipContext);
assert.equal(vm.runInContext('_getLipSyncTarget()',lipContext),0,'Silence must close mouth');
lipContext._analyser.getByteTimeDomainData=data=>data.fill(140);
const open=vm.runInContext('_getLipSyncTarget()',lipContext);
assert(open>0&&open<0.85,'Speech energy opens mouth without saturating');
console.log('Speech-start motion scheduling and cancellation checks passed');
