const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('integrated.html','utf8');
const start=html.indexOf('let _ttsGeneration=0;');
const end=html.indexOf('let _ttsCapabilityPromise',start);
const timers=[];
const context=vm.createContext({setTimeout:(fn,delay)=>{timers.push({fn,delay});return timers.length;}});
vm.runInContext(html.slice(start,end),context);
vm.runInContext('var calls=0;_speechStartAction=()=>calls++;notifySpeechStarted(0,120);notifySpeechStarted(0,120);',context);
assert.equal(timers.length,1,'Only first audio chunk schedules motion');
assert.equal(timers[0].delay,120,'Respect actual scheduled audio start');
timers[0].fn();
assert.equal(vm.runInContext('calls',context),1);
vm.runInContext('notifySpeechStarted(0)',context);
assert.equal(timers.length,1,'Do not replay motion for later chunks');
vm.runInContext('_speechStartAction=()=>calls++;notifySpeechStarted(0);_ttsGeneration++;',context);
timers[1].fn();
assert.equal(vm.runInContext('calls',context),1,'Cancelled audio must not trigger stale motion');
assert(!html.includes('setTimeout(()=>playMotion(msg.motion),200)'));
console.log('Speech-start motion scheduling and cancellation checks passed');
