const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('integrated.html','utf8');
const start=html.indexOf('function createVoiceEndpoint()'),end=html.indexOf('function disableContinuousVoice()',start);
const ctx=vm.createContext({});vm.runInContext(html.slice(start,end),ctx);
const create=()=>vm.runInContext('createVoiceEndpoint()',ctx);
let vad=create(),state;
for(let i=0;i<300;i++) state=vad.feed(0.004,0.1);
assert(!state.done);assert(state.idle,'Silence expires without submitting audio');
vad=create();state=vad.feed(0.08,0.1);assert(!state.started,'Single click is not sustained speech');
state=vad.feed(0.001,0.1);assert(!state.started);
for(let i=0;i<5;i++) state=vad.feed(0.06,0.1);
assert(state.started);
for(let i=0;i<8;i++) state=vad.feed(0.001,0.1);
assert(!state.done,'Short natural pause must not cut a sentence');
state=vad.feed(0.06,0.1);assert(!state.done,'Speaking resets the silence window');
for(let i=0;i<13;i++) state=vad.feed(0.001,0.1);
assert(state.done,'Sustained silence ends a voiced utterance');
assert(!html.includes('generation!==_voiceGeneration||epoch!==_continuousEpoch'),'New press must not cancel an already confirmed recording upload');
assert(html.includes('if(epoch!==_continuousEpoch) return'),'Continuous-mode epoch still rejects obsolete recordings');
assert(html.includes('generation!==_voiceGeneration'),'Pending microphone permission can be cancelled');
assert(html.includes("if(_voiceMode==='browser'&&shouldSend)"),'浏览器识别回退也必须等待移动端松手后发送');
assert(html.includes("if(_holdToTalkActive)finishHoldToTalk(null,true)"),'按住说话达到最长录音时间后必须自动发送');
assert(html.includes("_holdCancelPending=(Number(event.clientY)||0)<_holdStartY-56"),'按住说话必须支持上滑取消');
assert(html.includes("window.addEventListener('pointerup'"),'手指移出按钮后仍必须捕获松手并发送');
assert(html.includes("refreshAsrStatus();\n    const knownUnavailable"),'ASR状态刷新不得阻塞移动端麦克风权限手势');
console.log('自动停顿、短停顿保持、无声超时与迟到录音保护测试通过');
